import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const certsDir = path.join(fileURLToPath(new URL('.', import.meta.url)), '..', 'certs');

// Use the self-signed cert generated by the backend (start backend first once to create certs/)
const tlsOptions = (() => {
  try {
    return {
      cert: fs.readFileSync(path.join(certsDir, 'cert.pem')),
      key:  fs.readFileSync(path.join(certsDir, 'key.pem')),
    };
  } catch {
    console.warn('[vite] certs/ not found — running HTTP. Start the backend once first to generate certs, then restart Vite.');
    return undefined;
  }
})();

export default defineConfig({
  plugins: [react(), tailwindcss()],
  server: {
    port: 5173,
    host: true,
    https: tlsOptions,
    proxy: {
      '/api': {
        target: 'http://localhost:3000',
        changeOrigin: true,
      },
      '/uploads': {
        target: 'http://localhost:3000',
        changeOrigin: true,
      },
    },
  },
  build: {
    outDir: '../frontend-dist',
  },
});
